# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    snapshot
    frameit
    time = Time.new.strftime("%Y%m%d%H%M")
    increment_build_number(build_number: time) # присваивание номера билда в виде текущей даты

	# snapshot # скриншоты
	# produce # выгрузка приложения в App Store Connect
	# cert # установки сертификатов и provision profiles
	# sigh # по умолчанию создаст, восстановит и загрузит профили для App Store.
	# gym # ipa файл нашего приложения
	# upload_to_testflight(
        #  skip_submission: true, # будем использовать только для загрузки ipa файла
        #  skip_waiting_for_build_processing: true # не дожидаемся окончания processing'a
      	# )

  end
end

# gym С заданием конкретных параметров:
      #
      # gym(
      #  workspace: "TheHatGame.xcworkspace",
      #  scheme: "TheHatGame",
      #  configuration: "Release",
      #  clean: true,
      #  output_directory: "./build",
      #  output_name: "TheHatGame.ipa",
      #  codesigning_identity: "iPhone Distribution: Evgeny Shishko"
      # )
